services:
  mast3r-slam:
    build: .
    container_name: mast3r-slam-container
    stdin_open: true # Keep stdin open for the container
    command: tail -f /dev/null
    tty: true # Allocate a pseudo-TTY (required for an interactive shell)
    shm_size: '2gb'  # Increase shared memory size for multiprocessing
    volumes:
      - /fdata2/nati_n/master-slam/workspace:/data
      - ./output:/app/output
      - ./scripts:/app/scripts
      - ./checkpoints:/app/checkpoints
      - ./config:/app/config
      - /tmp/.X11-unix:/tmp/.X11-unix
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - DISPLAY=${DISPLAY} # Pass the host's display to the container
      - NVIDIA_VISIBLE_DEVICES=all # Make all GPUs visible to the container
    ipc: host
    network_mode: host # Use host network mode for X11 forwarding